name: ESLint

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Instel dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
